---
language: python
python:   "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get remove -qq --purge nfs-common nfs-kernel-server

install:
  - pip install ansible

script:
  # Test defaut behavior
  - ansible-playbook tests/test_defaults.yml -i localhost, --syntax-check 
  - ansible-playbook tests/test_defaults.yml -i localhost, --connection=local --sudo -vvv

  # Test server configuration
  - ansible-playbook tests/test_server.yml   -i localhost, --syntax-check 
  - ansible-playbook tests/test_server.yml   -i localhost, --connection=local --sudo -vvv

# vi:ts=2:sw=2:et:ft=yaml
