---

- name: NFS Server config
  template:
    src=etc/default/nfs-kernel-server.j2
    dest=/etc/default/nfs-kernel-server
  notify: nfs-server restart

- name: Create exported Mount Points
  file:
    state=directory
    dest="{{item.mpoint_src}}"
    mode="{{item.mode|default('0755')}}"
  with_items: nfs_exports
  when: nfs_exports is defined

- name: Check ownership
  file:
    state=directory
    dest="{{item.mpoint_src}}"
    owner="{{item.owner|default(nfs_default_owner)}}"
  when: nfs_exports is defined and item.owner is defined
  with_items: nfs_exports

- name: Directory /etc/exports.d
  file:
    state=directory
    dest="/etc/exports.d"
    owner="root"
    mode="0755"

- name: Exports
  template:
    src=etc/exports.d/exports.j2
    dest="/etc/exports.d/{{item.export_file}}.exports"
    owner="root"
    group="root"
    mode="644"
  with_items: nfs_exports
  when: nfs_exports is defined
  notify: nfs-server reload

# vi:ts=2:sw=2:et:ft=yaml
