---

- include: install.yml
  tags: nfs_install

- include: config_server.yml
  tags: nfs_server
  when: is_nfs_server

- include: config_client.yml
  tags: nfs_client
  when: is_nfs_client

- name: Enable NFS Server
  service:
    name=nfs-kernel-server
    enabled=yes
    state=started
  when: is_nfs_server

# vi:ts=2:sw=2:et:ft=yaml
